### ISSUE TITLE
Using enumitem on a cheetsheet seems to cause -{}- to render as en-dash

### ISSUE THREAD

**Issue by fullerth** [ACHinrichs/LaTeX-templates#13]
I've asked this over on the [Tex stack-overflow](https://tex.stackexchange.com/questions/420344/using-enumitem-on-a-cheetsheet-seems-to-cause-to-render-as-en-dash), but figured I should also create an issue here.

I'm using this [cheatsheet class](https://github.com/ACHinrichs/LaTeX-templates/tree/master/cheatsheet) to create a git cheatsheet.

I have a couple commands the are too long for a single line, so I added the `enumitem` package to use the `[style=unboxed]` to force lines to wrap. They now wrap, but `-{}-` now reduces to an en-dash instead of `--`

Reproducable by adding [cheatsheet.cls](https://github.com/ACHinrichs/LaTeX-templates/blob/master/cheatsheet/cheatsheet.cls)
to a ShareLatex project with the following document:

```
    \documentclass[columns=3]{cheatsheet}
    \usepackage[utf8]{inputenc}
    \usepackage{enumitem}
    
    \title{Test En-dash}
    \author{ }
    \date{March 2018}
    
    \begin{document}
    
    \maketitle
    
    \newcommand{\gitcmd}[2]{\item[\small\texttt{\$ #1}] \hfill \\ #2}
    
    \section{Configuration}
    \begin{description}[style=unboxed]
    \gitcmd{git config -{}-global user.name "<name>"}{Sets the name to be attached to your commits }
    \gitcmd{git config -{}-global user.email "<email address>"}{Set to your email}
    \end{description}
    
    \section{Commit History}
    \begin{description}%[style=unboxed]
    \gitcmd{git log}{Display the version history of the current branch}
    \gitcmd{git log -{}-oneline}{Display version history oneline summaries}
    \end{description}
    
    \end{document}
    \documentclass[columns=3]{cheatsheet}
    \usepackage[utf8]{inputenc}
    \usepackage{enumitem}
    
    \title{Test En-dash}
    \author{ }
    \date{March 2018}
    
    \begin{document}
    
    \maketitle
    
    \newcommand{\gitcmd}[2]{\item[\small\texttt{\$ #1}] \hfill \\ #2}
    
    \section{Configuration}
    \begin{description}[style=unboxed]
    \gitcmd{git config -{}-global user.name "<name>"}{Sets the name to be attached to your commits }
    \gitcmd{git config -{}-global user.email "<email address>"}{Set to your email}
    \end{description}
    
    \section{Commit History}
    \begin{description}%[style=unboxed]
    \gitcmd{git log}{Display the version history of the current branch}
    \gitcmd{git log -{}-oneline}{Display version history oneline summaries}
    \end{description}
    
    \end{document}
```

Toggling the `[style=unboxed]` comment on the two `descriptions` changes how `-{}-` is rendered. Adding a space between the dash and word (`-{}- global`) also works, but isn't a valid git command.

This appears to be a problem with `cheetsheet.cls`, as it does not occur if using the parent `article` class.

**Comment by ACHinrichs** [comment]
I will look into it

**Comment by ACHinrichs** [comment]
It seems to be some form of issue between the `libertine` font and `multicols`

I found a quick workaround, which simply sets the Typewriter-font to computer-modern-tt:
```
\renewcommand{\ttdefault}{cmtt}
```

**Comment by ACHinrichs** [comment]
[This](https://www.amazon.de/Amscan-Casino-Konfetti-Pack-von/dp/B00DT56ZDY/ref=sr_1_1?s=kitchen&ie=UTF8&qid=1521120103&sr=1-1&keywords=poker+streudeko) SO answer seems to explain what happens, I do not fully understand when and why it happens, though.

I will investigate further, but if this is true, then this is a wontfix

**Comment by fullerth** [comment]
Yep, that's totally fair to make this a wontfix.

I also don't quite understand boxed vs unboxed labels.

Thanks for creating this class. It's been really useful for me!

**Comment by occloxium** [comment]
Seems you copied the wrong link

**Comment by fullerth** [comment]
https://tex.stackexchange.com/a/420358/11349 is the intended link

**Comment by ACHinrichs** [comment]
> https://tex.stackexchange.com/a/420358/11349 is the intended link

Indeed, it is, I updated my comment

**Comment by occloxium** [comment]
Rather than styling your commands with `\texttt{...}` and risk LaTeX messing up your commands, and since you already defined a wrapper command for your command items, you would be better off using `\verb|...|` or `\begin{verbatim}...\end{verbatim}`.

Your `gitcmd` command would look like  
````
\newcommand{\gitcmd}[2]{\item[\small\verb|$ #1|] \hfill \\ #2}
````

Note that neither $ nor -- need escaping or hacking (-{}-) anymore and you can directly copy your git commands into the parameters for your smart macro.
